### ISSUE TITLE
iconpicker with fontawesome empty

### ISSUE THREAD

**Issue by ydakilux** [Insolita/yii2-iconpicker#3]
Hello,

 If I use the iconpicker in my view like in the sample code : 

    <?= $form->field($model, 'icon')->widget('\insolita\iconpicker\Iconpicker',
     [
       'clientOptions'=>['rows'=>8,'cols'=>10,'placement'=>'right'],
     ])->label('Icon'); ?>

I can see the iconpicker and the icons, but if I try to use it with the fontawesome, the iconpicker show, but he's empty

    <?= $form->field($model, 'icon')->widget('\insolita\iconpicker\Iconpicker',
     [
       'iconset'=>'fontawesome',
       'clientOptions'=>['rows'=>8,'cols'=>10,'placement'=>'right'],
     ])->label('Icon'); ?>

 I'm using Yii 2.0.12 and  PHP 5.6.30-0+deb8u1

fontAwesome css is loaded : 
     < link href="/assets/52647793/css/font-awesome.min.css" rel="stylesheet">
and 
fontawesome js is also loaded
          < script src="/assets/bcd69a99/bootstrap-iconpicker/js/iconset/iconset-fontawesome-4.3.0.js"></script>

  please advice,

          thanks

**Comment by Insolita** [comment]
upgrade to new version; Unfortunately, original plugin source seems dead, i replace it
