### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by vdvb** [Insolita/yii2-iconpicker#6]
I tryed to install your extension but i got this proble(below line).How can i resolve this?
Thx in advance
Bert

-------------------------------------------------------------------------------------------------
composer require --prefer-dist insolita/yii2-iconpicker "^3.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for insolita/yii2-iconpicker ^3.0 -> satisfiable by insolita/yii2-iconpicker[3.0.0].
    - insolita/yii2-iconpicker 3.0.0 requires bower-asset/eliberty-bootstrap-iconpicker 1.8.1 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by Insolita** [comment]
what yii version you use?

**Comment by Insolita** [comment]
The required  package exists
 https://asset-packagist.org/package/bower-asset/eliberty-bootstrap-iconpicker
https://bower.io/search/?q=eliberty-bootstrap-iconpicker
Check you composer configuration

**Comment by vdvb** [comment]
Yii2

**Comment by vdvb** [comment]
i think it works right now -> same command.

**Comment by vdvb** [comment]
Everything works now even doh i didn't change anything. :-)
Excellent job  .
thx for the quick reply.
